dist: trusty
language: node_js
notifications:
  email: false
node_js: lts/*
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - yarn prettier:check
        - npm test
        - npm build
      deploy:
        # provider: script
        # script: npm run semantic-release
        # skip_cleanup: true
        # keep_history: true
        # on:
        #   tags: false
        #   all_branches: true
        #   condition: $TRAVIS_BRANCH =~ ^(master|next)$